coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,files"
  require_changes: true
